### PR TITLE
Change UI design

### PR DESCRIPTION
**Pull request by lislia**
Add a scroll bar for projects (if there are more than 4, you can scroll the project gallery horizontally), add animations on hover, change colour scheme, add cursor animation (e.g. block once it is funded), update layouts

### CODE REVIEW

**Comment by SSardorf** [comment]
Looks good to me! Although perhaps we should try to hide the scrollbar like so https://stackoverflow.com/questions/66416614/how-to-create-scrollable-element-in-tailwind-without-a-scrollbar

**Comment by SSardorf** [comment]
One issue though, the create new projects form overflows causing the background to be white (for some reason)
image

**Comment by lislia** [comment]
Hmm I thought I solved it! Oki I will look into it later

**Comment by SSardorf** [comment]
You can merge this and make a new branch for the fix though

**Comment by SSardorf** [comment]
Also - The github icon doesn't take me to the github. It doesn't link to anything currently

**Comment by lislia** [comment]
Yes sure. Will check the link as well

**Pull request merged**
